# 🚗 Analyse Statistique Avancée des Accidents de la Route aux États-Unis

## Importer data

In [4]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor
import joblib

#Importer data
df= pd.read_csv("us.csv")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 47 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             500000 non-null  int64
 1   ID                     500000 non-null  object
 2   Source                 500000 non-null  object
 3   Severity               500000 non-null  int64
 4   Start_Time             500000 non-null  object
 5   End_Time               500000 non-null  object
 6   Start_Lat              500000 non-null  float64
 7   Start_Lng              500000 non-null  float64
 8   End_Lat                0 non-null       float64
 9   End_Lng                0 non-null       float64
 10  Distance(mi)           500000 non-null  float64
 11  Description            500000 non-null  object
 12  Street                 500000 non-null  object
 13  City                   499978 non-null  object
 14  County                 500000 non-null  object
 15  State                  500000 non-null  object
 16  Zipcode                499942 non-null  object
 17  Country                500000 non-null  object
 18  Timezone               499942 non-null  object
 19  Airport_Code           499940 non-null  object
 20  Weather_Timestamp      495885 non-null  object
 21  Temperature(F)         492750 non-null  float64
 22  Wind_Chill(F)          62359 non-null   float64
 23  Humidity(%)            492085 non-null  float64
 24  Pressure(in)           494261 non-null  float64
 25  Visibility(mi)         489461 non-null  float64
 26  Wind_Direction         495853 non-null  object
 27  Wind_Speed(mph)        410960 non-null  float64
 28  Precipitation(in)      51946 non-null   float64
 29  Weather_Condition      489815 non-null  object
 30  Amenity                500000 non-null  bool
 31  Bump                   500000 non-null  bool
 32  Crossing               500000 non-null  bool
 33  Give_Way               500000 non-null  bool
 34  Junction               500000 non-null  bool
 35  No_Exit                500000 non-null  bool
 36  Railway                500000 non-null  bool
 37  Roundabout             500000 non-null  bool
 38  Station                500000 non-null  bool
 39  Stop                   500000 non-null  bool
 40  Traffic_Calming        500000 non-null  bool
 41  Traffic_Signal         500000 non-null  bool
 42  Turning_Loop           500000 non-null  bool
 43  Sunrise_Sunset         499978 non-null  object
 44  Civil_Twilight         499978 non-null  object
 45  Nautical_Twilight      499978 non-null  object
 46  Astronomical_Twilight  499978 non-null  object
dtypes: bool(13), float64(12), int64(2), object(20)
memory usage: 135.9+ MB
None

## Nettoyage

In [ ]:
# Colonnes à supprimer
drop_cols = [
    "Country", "Source", "Turning_Loop",
    "Description", "Street", "Zipcode",
    "Airport_Code", "Timezone",
    "Nautical_Twilight", "Astronomical_Twilight"
]

# Dtypes optimisés (hors colonnes supprimées)
dtype_map = {
    "ID": "string",
    "Severity": "int8",
    "Start_Lat": "float32",
    "Start_Lng": "float32",
    "End_Lat": "float32",
    "End_Lng": "float32",
    "Distance(mi)": "float32",
    "City": "category",
    "County": "category",
    "State": "category",
    "Temperature(F)": "float32",
    "Wind_Chill(F)": "float32",
    "Humidity(%)": "float32",
    "Pressure(in)": "float32",
    "Visibility(mi)": "float32",
    "Wind_Direction": "category",
    "Wind_Speed(mph)": "float32",
    "Precipitation(in)": "float32",
    "Weather_Condition": "category",
    "Sunrise_Sunset": "category",
    "Civil_Twilight": "category",
}

bool_cols = [
    "Amenity","Bump","Crossing","Give_Way","Junction","No_Exit",
    "Railway","Roundabout","Station","Stop","Traffic_Calming","Traffic_Signal"
]

# -------------------------------
# CHARGEMENT DU FICHIER 500K
# -------------------------------
df = pd.read_csv(
    "us.csv",
    dtype=dtype_map,
    parse_dates=["Start_Time", "End_Time", "Weather_Timestamp"],
    low_memory=False
)

# Conversion en bool
for col in bool_cols:
    df[col] = df[col].astype("boolean")

# Suppression colonnes inutiles
df.drop(columns=drop_cols, errors="ignore", inplace=True)

print("Colonnes supprimées :", drop_cols)

In [ ]:
# Conversion Fahrenheit -> Celsius
df["Temperature(C)"] = (df["Temperature(F)"] - 32) * 5/9
df.drop(columns=["Temperature(F)"], inplace=True)
df["Wind_Chill(C)"] = (df["Wind_Chill(F)"] - 32) * 5/9
df.drop(columns=["Wind_Chill(F)"], inplace=True)

In [29]:
# Suppression doublons
df.drop_duplicates(subset=["ID"], inplace=True)
df.reset_index(drop=True, inplace=True)
print("Doublons supprimés. Nouvelle taille :", df.shape)

Doublons supprimés. Nouvelle taille : (500000, 38)

In [ ]:
# Résumé des colonnes
pd.DataFrame({
    "Column": df.columns,
    "Dtype": df.dtypes.values,
    "Missing Values": df.isna().sum().values
})

               Column           Dtype  Missing Values
0          Unnamed: 0           int64               0
1                  ID  string[python]               0
2            Severity            int8               0
3          Start_Time  datetime64[ns]               0
4            End_Time  datetime64[ns]               0
5           Start_Lat         float32               0
6           Start_Lng         float32               0
7        Distance(mi)         float32               0
8                City  string[python]               0
9              County        category               0
10              State        category               0
11  Weather_Timestamp  datetime64[ns]            4115
12      Wind_Chill(F)         float32          437641
13        Humidity(%)         float32            7915
14       Pressure(in)         float32            5739
15     Visibility(mi)         float32           10539
16     Wind_Direction  string[python]               0
17    Wind_Speed(mph)         float32           89040
18  Precipitation(in)         float32          448054
19  Weather_Condition  string[python]               0
20            Amenity         boolean               0
21               Bump         boolean               0
22           Crossing         boolean               0
23           Give_Way         boolean               0
24           Junction         boolean               0
25            No_Exit         boolean               0
26            Railway         boolean               0
27         Roundabout         boolean               0
28            Station         boolean               0
29               Stop         boolean               0
30    Traffic_Calming         boolean               0
31     Traffic_Signal         boolean               0
32     Sunrise_Sunset  string[python]               0
33     Civil_Twilight  string[python]               0
34     Temperature(C)         float32            7250
35              month            int8               0
36               hour            int8               0
37            cluster            int8               0

In [26]:
# Forward fill pour Weather_Timestamp
df = df.sort_values("Start_Time")
df["Weather_Timestamp"] = df["Weather_Timestamp"].ffill()

# Colonnes météo à traiter
weather_cols = [
    "Temperature(C)", "Humidity(%)", "Pressure(in)",
    "Visibility(mi)", "Wind_Speed(mph)",
    "Wind_Chill(F)", "Precipitation(in)"
]

# Remplissage temporaire pour Wind_Chill et Precipitation
df["Wind_Chill(F)"] = df["Wind_Chill(F)"].fillna(0)
df["Precipitation(in)"] = df["Precipitation(in)"].fillna(0)

# Imputation avancée pour les autres colonnes météo numériques
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor

imputer = IterativeImputer(
    estimator=RandomForestRegressor(n_estimators=30, max_depth=6, n_jobs=-1),
    max_iter=5,
    random_state=42
)

# Colonnes à imputer (sauf Wind_Chill et Precipitation qui sont déjà remplis)
cols_to_impute = ["Temperature(C)", "Humidity(%)", "Pressure(in)", "Visibility(mi)", "Wind_Speed(mph)"]

df[cols_to_impute] = imputer.fit_transform(df[cols_to_impute])

# Optimisation mémoire
for c in cols_to_impute + ["Wind_Chill(F)", "Precipitation(in)"]:
    df[c] = df[c].astype("float32")

print("✅ Nettoyage et imputation terminés pour l'échantillon 500K")

✅ Nettoyage et imputation terminés pour l'échantillon 500K

c:\Users\leila\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [ ]:
# Résumé des colonnes
pd.DataFrame({
    "Column": df.columns,
    "Dtype": df.dtypes.values,
    "Missing Values": df.isna().sum().values
})

               Column           Dtype  Missing Values
0          Unnamed: 0           int64               0
1                  ID  string[python]               0
2            Severity            int8               0
3          Start_Time  datetime64[ns]               0
4            End_Time  datetime64[ns]               0
5           Start_Lat         float32               0
6           Start_Lng         float32               0
7        Distance(mi)         float32               0
8                City  string[python]               0
9              County        category               0
10              State        category               0
11  Weather_Timestamp  datetime64[ns]               0
12      Wind_Chill(F)         float32               0
13        Humidity(%)         float32               0
14       Pressure(in)         float32               0
15     Visibility(mi)         float32               0
16     Wind_Direction  string[python]               0
17    Wind_Speed(mph)         float32               0
18  Precipitation(in)         float32               0
19  Weather_Condition  string[python]               0
20            Amenity         boolean               0
21               Bump         boolean               0
22           Crossing         boolean               0
23           Give_Way         boolean               0
24           Junction         boolean               0
25            No_Exit         boolean               0
26            Railway         boolean               0
27         Roundabout         boolean               0
28            Station         boolean               0
29               Stop         boolean               0
30    Traffic_Calming         boolean               0
31     Traffic_Signal         boolean               0
32     Sunrise_Sunset  string[python]               0
33     Civil_Twilight  string[python]               0
34     Temperature(C)         float32               0
35              month            int8               0
36               hour            int8               0
37            cluster            int8               0